### ISSUE TITLE
Ship Monster- problem 

### ISSUE THREAD

**Issue by wojwlo1** [aniakoczyk/Bialystok#8]
Jak zrobić, żeby każdy Ship Monster strzelał, a nie tylko jeden???? 
I jak zrobić by po trafieniu jednego inny mógł nadal strzelać???

**Comment by daniiszewska** [comment]
może jakby zamiast tej pętli:

num_of_ship_monster = 10
for i in range (num_of_ship_monster):
    ship_monster = Ship_monster()
    all_sprites_group.add(ship_monster)
    enemies_group.add(ship_monster)
    ship_monsters_group.add(ship_monster)

stworzyć ich pojedynczo, bo może on ich traktuje jako grupę wrogów i w ramach grupy strzela 1

**Comment by wojwlo1** [comment]
próbowałem robić 
for i in range (num_of_ship_monster):
ship_monster_i = Ship_monster()
all_sprites_group.add(ship_monste_ir)
enemies_group.add(ship_monster_i)
ship_monsters_group.add(ship_monster_i)

i później wywoływał metodę tez ship_monster_i

i nie wiem dlaczego nie działało, możesz spróbować

**Comment by wojwlo1** [comment]
zrobiłem pętle, zamykam problem

num_of_ship_monster = 100
ship_monster = Ship_monster()


ship_monsters_list = []
for i in range (num_of_ship_monster):
    ship_monster_i = Ship_monster()
    ship_monsters_list.append(ship_monster_i)


for item in ship_monsters_list:
    enemies_group.add(item)
    all_sprites_group.add(item)
    ship_monsters_group.add(item)
